// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cppCycle
List cppCycle(int L, int K, int J, int it1, int it2, int it3, int itprint, double prilev2, double prilev1, double priresp, double priresp2, bool estimates, bool doVar2, IntegerVector sel, int T2, IntegerVector ncat2, IntegerMatrix Y2, IntegerMatrix R2, List nlat2, List piresp2, IntegerVector nj, int T, IntegerVector ncat, List datJ, List R, List npattern, List pat, IntegerVector w, List z, List nresp, List piresp, List pclasslev1, NumericMatrix jointlev2, NumericVector grouploglik, double loglik, NumericVector nlatw, NumericMatrix nlatpk, NumericMatrix piK, NumericVector piW, List imp, List imp2, int nimp, bool count, NumericVector piWm, NumericMatrix piKm, List pirespm, List piresp2m, NumericVector piWs, NumericMatrix piKs, List piresps, List piresp2s, double f, bool plotloglik, NumericVector pllk, NumericMatrix condp1, IntegerVector npattern2, IntegerVector pat2, double scale);
RcppExport SEXP _BMLCimpute_cppCycle(SEXP LSEXP, SEXP KSEXP, SEXP JSEXP, SEXP it1SEXP, SEXP it2SEXP, SEXP it3SEXP, SEXP itprintSEXP, SEXP prilev2SEXP, SEXP prilev1SEXP, SEXP prirespSEXP, SEXP priresp2SEXP, SEXP estimatesSEXP, SEXP doVar2SEXP, SEXP selSEXP, SEXP T2SEXP, SEXP ncat2SEXP, SEXP Y2SEXP, SEXP R2SEXP, SEXP nlat2SEXP, SEXP piresp2SEXP, SEXP njSEXP, SEXP TSEXP, SEXP ncatSEXP, SEXP datJSEXP, SEXP RSEXP, SEXP npatternSEXP, SEXP patSEXP, SEXP wSEXP, SEXP zSEXP, SEXP nrespSEXP, SEXP pirespSEXP, SEXP pclasslev1SEXP, SEXP jointlev2SEXP, SEXP grouploglikSEXP, SEXP loglikSEXP, SEXP nlatwSEXP, SEXP nlatpkSEXP, SEXP piKSEXP, SEXP piWSEXP, SEXP impSEXP, SEXP imp2SEXP, SEXP nimpSEXP, SEXP countSEXP, SEXP piWmSEXP, SEXP piKmSEXP, SEXP pirespmSEXP, SEXP piresp2mSEXP, SEXP piWsSEXP, SEXP piKsSEXP, SEXP pirespsSEXP, SEXP piresp2sSEXP, SEXP fSEXP, SEXP plotloglikSEXP, SEXP pllkSEXP, SEXP condp1SEXP, SEXP npattern2SEXP, SEXP pat2SEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type it1(it1SEXP);
    Rcpp::traits::input_parameter< int >::type it2(it2SEXP);
    Rcpp::traits::input_parameter< int >::type it3(it3SEXP);
    Rcpp::traits::input_parameter< int >::type itprint(itprintSEXP);
    Rcpp::traits::input_parameter< double >::type prilev2(prilev2SEXP);
    Rcpp::traits::input_parameter< double >::type prilev1(prilev1SEXP);
    Rcpp::traits::input_parameter< double >::type priresp(prirespSEXP);
    Rcpp::traits::input_parameter< double >::type priresp2(priresp2SEXP);
    Rcpp::traits::input_parameter< bool >::type estimates(estimatesSEXP);
    Rcpp::traits::input_parameter< bool >::type doVar2(doVar2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sel(selSEXP);
    Rcpp::traits::input_parameter< int >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ncat2(ncat2SEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type R2(R2SEXP);
    Rcpp::traits::input_parameter< List >::type nlat2(nlat2SEXP);
    Rcpp::traits::input_parameter< List >::type piresp2(piresp2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nj(njSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ncat(ncatSEXP);
    Rcpp::traits::input_parameter< List >::type datJ(datJSEXP);
    Rcpp::traits::input_parameter< List >::type R(RSEXP);
    Rcpp::traits::input_parameter< List >::type npattern(npatternSEXP);
    Rcpp::traits::input_parameter< List >::type pat(patSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< List >::type z(zSEXP);
    Rcpp::traits::input_parameter< List >::type nresp(nrespSEXP);
    Rcpp::traits::input_parameter< List >::type piresp(pirespSEXP);
    Rcpp::traits::input_parameter< List >::type pclasslev1(pclasslev1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type jointlev2(jointlev2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grouploglik(grouploglikSEXP);
    Rcpp::traits::input_parameter< double >::type loglik(loglikSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nlatw(nlatwSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nlatpk(nlatpkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type piK(piKSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type piW(piWSEXP);
    Rcpp::traits::input_parameter< List >::type imp(impSEXP);
    Rcpp::traits::input_parameter< List >::type imp2(imp2SEXP);
    Rcpp::traits::input_parameter< int >::type nimp(nimpSEXP);
    Rcpp::traits::input_parameter< bool >::type count(countSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type piWm(piWmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type piKm(piKmSEXP);
    Rcpp::traits::input_parameter< List >::type pirespm(pirespmSEXP);
    Rcpp::traits::input_parameter< List >::type piresp2m(piresp2mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type piWs(piWsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type piKs(piKsSEXP);
    Rcpp::traits::input_parameter< List >::type piresps(pirespsSEXP);
    Rcpp::traits::input_parameter< List >::type piresp2s(piresp2sSEXP);
    Rcpp::traits::input_parameter< double >::type f(fSEXP);
    Rcpp::traits::input_parameter< bool >::type plotloglik(plotloglikSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pllk(pllkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type condp1(condp1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type npattern2(npattern2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pat2(pat2SEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(cppCycle(L, K, J, it1, it2, it3, itprint, prilev2, prilev1, priresp, priresp2, estimates, doVar2, sel, T2, ncat2, Y2, R2, nlat2, piresp2, nj, T, ncat, datJ, R, npattern, pat, w, z, nresp, piresp, pclasslev1, jointlev2, grouploglik, loglik, nlatw, nlatpk, piK, piW, imp, imp2, nimp, count, piWm, piKm, pirespm, piresp2m, piWs, piKs, piresps, piresp2s, f, plotloglik, pllk, condp1, npattern2, pat2, scale));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BMLCimpute_cppCycle", (DL_FUNC) &_BMLCimpute_cppCycle, 58},
    {NULL, NULL, 0}
};

RcppExport void R_init_BMLCimpute(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
