# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppCycle <- function(L, K, J, it1, it2, it3, itprint, prilev2, prilev1, priresp, priresp2, estimates, doVar2, sel, T2, ncat2, Y2, R2, nlat2, piresp2, nj, T, ncat, datJ, R, npattern, pat, w, z, nresp, piresp, pclasslev1, jointlev2, grouploglik, loglik, nlatw, nlatpk, piK, piW, imp, imp2, nimp, count, piWm, piKm, pirespm, piresp2m, piWs, piKs, piresps, piresp2s, f, plotloglik, pllk, condp1, npattern2, pat2, scale) {
    .Call(`_BMLCimpute_cppCycle`, L, K, J, it1, it2, it3, itprint, prilev2, prilev1, priresp, priresp2, estimates, doVar2, sel, T2, ncat2, Y2, R2, nlat2, piresp2, nj, T, ncat, datJ, R, npattern, pat, w, z, nresp, piresp, pclasslev1, jointlev2, grouploglik, loglik, nlatw, nlatpk, piK, piW, imp, imp2, nimp, count, piWm, piKm, pirespm, piresp2m, piWs, piKs, piresps, piresp2s, f, plotloglik, pllk, condp1, npattern2, pat2, scale)
}

